[libraries.fixed_point]
files = [ 
"./source/hVHDL_memory_library/fpga_ram/ram_configuration/ram_configuration_16x1024_pkg.vhd",
"./source/hVHDL_memory_library/fpga_ram/ram_read_port_pkg.vhd",

"./fixed_point_scaling/fixed_point_scaling_pkg.vhd",

"./multiplier/configuration/multiply_with_1_input_and_output_registers_pkg.vhd",
"./multiplier/multiplier_base_types_18bit_pkg.vhd",
"./real_to_fixed/real_to_fixed_pkg.vhd",

"./multiplier/multiplier_pkg.vhd",
"./sincos/sincos_pkg.vhd",

"./sincos/lut_generator_functions/sine_lut_generator_pkg.vhd",
"./sincos/lut_sine_pkg.vhd",

"./division/division_internal_pkg.vhd",
"./division/division_pkg.vhd",
"./first_order_filter/first_order_filter_pkg.vhd",
"./pi_controller/pi_controller_pkg.vhd",

"./coordinate_transforms/abc_to_ab_transform/abc_to_ab_transform_pkg.vhd",
"./coordinate_transforms/abc_to_ab_transform/ab_to_abc_transform_pkg.vhd",
"./coordinate_transforms/ab_to_dq_transform/dq_to_ab_transform_pkg.vhd",
"./coordinate_transforms/ab_to_dq_transform/ab_to_dq_transform_pkg.vhd",

"./sos_filter/sos_filter_pkg.vhd",
"./testbenches/multiply_add/fixed_point_dsp_pkg.vhd",
"./sos_filter/dsp_sos_filter_pkg.vhd",

"./square_root/fixed_isqrt_pkg.vhd",
"./square_root/fixed_sqrt_pkg.vhd",
]
